### ISSUE TITLE
Error on create pod: invalid argument

### ISSUE THREAD

**Issue by feiskyer** [hyperhq/hyper#48] opened 2015-08-20 08:47 UTC
[HYPER ERROR 0820 01:28:^@26 42047 server.go] [:132] HTTP Error: statusCode=404 No such image: ubuntu (tag: latest)
[HYPER ERROR 0820 01:28:^@36 42047 pod.go] [:167] mkdir /var/lib/hyper/overlay/fb8ca8a983f6daca2289c5460992d7281d2a1d8f21d9eb6d91525042fd043ea9-init/merged/dev/shm: invalid argument
[HYPER ERROR 0820 01:28:^@36 42047 server.go] [:884] Handler for POST /pod/create returned error: mkdir /var/lib/hyper/overlay/fb8ca8a983f6daca2289c5460992d7281d2a1d8f21d9eb6d91525042fd043ea9-init/merged/dev/shm: invalid argument
[HYPER ERROR 0820 01:28:^@36 42047 server.go] [:132] HTTP Error: statusCode=500 mkdir /var/lib/hyper/overlay/fb8ca8a983f6daca2289c5460992d7281d2a1d8f21d9eb6d91525042fd043ea9-init/merged/dev/shm: invalid argument
[HYPER ERROR 0820 01:28:^@46 42047 pod.go] [:167] mkdir /var/lib/hyper/overlay/89a1e98aeb1a56498407592010d3747ed33ef962d6d1cf88c606a2a086bb3253-init/merged/dev/shm: invalid argument

**Comment by tuxknight** [comment] 2015-10-08 02:46
Same problem 
```
[root@registry hyper]# hyper run ubuntu:latest
```
```
hyper ERROR: Error from daemon's response: mkdir /var/lib/hyper/overlay/a7f45b97b668146329ddc343a121817a0e73916f2c413eeb8efe0c6b1c182a9a-init/merged/dev/shm: invalid argument
```
```
[root@registry hyper]# hyper info
Images: 4
Containers: 0
PODs: 0
Storage Driver: overlay
  Backing Filesystem: xfs
Hyper Root Dir: /var/lib/hyper
Index Server Address: https://index.docker.io/v1/
Execution Driver: kvm
Total Memory: 3.7 MB
Operating System: CentOS Linux 7 (Core)
```

**Comment by gnawux** [comment] 2015-10-08 03:20
@feiskyer does this problem still present in the HEAD of master?

**Comment by feiskyer** [comment] 2015-10-08 04:45
@gnawux No. I haven't encountered this problem since I updated hyper.

**Comment by gnawux** [comment] 2015-10-08 07:14
Thank you @feiskyer 

@tuxknight This issue has been fixed in master branch, and we will prepare a new release including this and other fixes soon.

**Comment by gnawux** [comment] 2015-11-05 07:23
@tuxknight 

Your issue seems to be caused by centOS kernel issue ref https://github.com/docker/docker/issues/10294

it is caused by CentOS 7.x + xfs backend fs + overlayfs storage engine, to work around this, use `devicemapper` instead. writing this line in configure file

```
StorageDriver=devicemapper
```

are you using CentOS 7.x?

**Comment by huikang** [comment] 2015-11-25 05:25
hi, @gnawux I am using centos7 too and tried add StorageDriver=devicemapper in /etc/hyper/config

```
ernel=/var/lib/hyper/kernel
Initrd=/var/lib/hyper/hyper-initrd.img
Bios=/var/lib/hyper/bios-qboot.bin
Cbfs=/var/lib/hyper/cbfs-qboot.rom
StorageDriver=devicemapper
```

However, after that, I can not start hyperd. Anything wrong with my config? Thanks.

**Comment by carmark** [comment] 2015-11-25 05:36
@huikang Could you please provide your log?

**Comment by gnawux** [comment] 2015-11-25 09:37
@huikang 

for centOS user, could you try the binary in this rpm

https://s3.amazonaws.com/hyper-install/hyper-0.4-1.el7.centos.src.rpm

I was working in build hyper native packages in hyper VMs, this is the first distro package to build, and I need some tester to try it.

Thank you.

**Comment by gnawux** [comment] 2015-11-25 09:43
and the SRPM is here https://s3.amazonaws.com/hyper-install/hyper-0.4-1.el7.centos.x86_64.rpm

**Closed** 2016-01-21 08:22 UTC
